### ISSUE TITLE
Link to Pull Terms is broken

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/FUNC-E#12]
It looks likes where you are pulling terms from: http://ftp.ebi.ac.uk/pub/databases/ changed their format mid-last month (8/16/22 for Interpro) and therefore the pull commands no longer work.  

Probably an easy fix, just need to update link. I would also suggest making it so it is obvious which version of terms the user is pulling when they run the command.

**Comment by JohnHadish** [comment]
Currently FUNC-E-terms uses this link:
```
http://ftp.ebi.ac.uk/pub/databases/interpro/entry.list
```
Should use this link:
```
http://ftp.ebi.ac.uk/pub/databases/interpro/current_release/entry.list
```

**Comment by spficklin** [comment]
Fixed.
