### ISSUE TITLE
FUNC-E uses deprecated python functions

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/FUNC-E#13]
FUNC-E uses `frame.append` which is a python function which will be deprecated soon. It suggest to change this to `pandas.concat` every time the progress bar increases when running it.

```
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  modResults = modResults.append({
```

**Comment by spficklin** [comment]
Fixed.
