### ISSUE TITLE
IPR Link is broken

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/FUNC-E#15]
In the `func_e/vocabs/ipr.py` file the link for IPR is broken and causes an error when trying to load the IPR terms.

We need some better code so that if the link doesn't work it reports it to the user.  Also, it may be good to let the user configure the links in case it happens again.

**Comment by nkran** [comment]
For the time being you could set it to `http://ftp.ebi.ac.uk/pub/databases/interpro/current_release/entry.list`. Happy to make a PR.

**Comment by spficklin** [comment]
Fixed on Jan 29th. Forgot to close this.
